import { useEffect, useMemo, useState } from 'react';
import PageLayout from '../components/PageLayout';
import Modal from '../components/Modal';
import { useToast } from '../components/Toast';
import { api } from '../utilities/ApiUtils';
import '../styles/admin.css';
import '../styles/v4.css';

const initial={productId:'',supplierId:'',quantity:1,notes:'',expectedDelivery:''};
export default function OrdersPage(){
 const toast=useToast();const [orders,setOrders]=useState([]),[products,setProducts]=useState([]),[suppliers,setSuppliers]=useState([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[statusOrder,setStatusOrder]=useState(null),[status,setStatus]=useState('PENDING'),[form,setForm]=useState(initial),[errors,setErrors]=useState({});
 const activeSuppliers=useMemo(()=>suppliers.filter(item=>item.active!==false),[suppliers]);
 const load=async()=>{setLoading(true);try{const [o,p,s]=await Promise.all([api.get('/orders'),api.get('/products/active'),api.get('/suppliers')]);setOrders(Array.isArray(o)?o:[]);setProducts(Array.isArray(p)?p:[]);setSuppliers(Array.isArray(s)?s:[])}catch(e){toast.error(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const chooseProduct=e=>{const value=e.target.value,product=products.find(p=>String(p.id)===value);setForm(current=>({...current,productId:value,supplierId:product?.supplierId?String(product.supplierId):current.supplierId}));setErrors(x=>({...x,productId:''}))};
 const validate=()=>{const next={};if(!form.productId)next.productId='Please select a product';if(!form.supplierId)next.supplierId='Please select a supplier';if(Number(form.quantity)<1)next.quantity='Quantity must be at least 1';setErrors(next);return !Object.keys(next).length};
 const place=async e=>{e.preventDefault();if(!validate())return;try{const next=await api.post('/orders',{...form,quantity:Number(form.quantity)});setOrders(list=>[next,...list]);setOpen(false);setForm(initial);toast.success('Order placed successfully')}catch(e){toast.error('Failed to place order. Please try again.')}};
 const saveStatus=async()=>{try{const next=await api.patch(`/orders/${statusOrder.id}/status`,{status});setOrders(list=>list.map(item=>item.id===next.id?next:item));setStatusOrder(null);toast.success('Order status updated')}catch(e){toast.error(e.message)}};
 const displayStatus=raw=>raw==='COMPLETED'?'RECEIVED':raw||'PENDING';
 return <PageLayout title="Orders"><div className="admin-heading"><div><h1>Orders</h1><p>Track purchase orders from request to receiving.</p></div><button className="btn-primary" onClick={()=>setOpen(true)}>+ Create Order</button></div><section className="settings-card resource-card"><div className="table-scroll"><table className="admin-table"><thead><tr><th>Order ID</th><th>Product Name</th><th>Supplier</th><th>Qty</th><th>Status</th><th>Date</th><th>Actions</th></tr></thead><tbody>{loading?[1,2,3].map(i=><tr className="skeleton-row" key={i}><td colSpan="7"><span/></td></tr>):orders.length?orders.map(row=><tr key={row.id}><td>#{row.referenceId||row.id}</td><td>{row.productName}</td><td>{row.supplierName}</td><td>{row.quantity}</td><td><span className={`order-status ${displayStatus(row.transactionStatus).toLowerCase()}`}>{title(displayStatus(row.transactionStatus))}</span></td><td>{formatDate(row.createdAt)}</td><td><div className="table-actions"><button className="row-btn edit" onClick={()=>{setStatusOrder(row);setStatus(row.transactionStatus||'PENDING')}}>Update</button></div></td></tr>):<tr><td colSpan="7"><EmptyOrders onAdd={()=>setOpen(true)}/></td></tr>}</tbody></table></div></section>
 <Modal isOpen={open} onClose={()=>setOpen(false)} title="Create New Order" size="md"><form className="modal-form order-form" onSubmit={place}><OrderSelect label="Product" required value={form.productId} onChange={chooseProduct} error={errors.productId}><option value="" disabled>— Select a product —</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} (SKU: {p.sku})</option>)}</OrderSelect><OrderSelect label="Supplier" required value={form.supplierId} onChange={e=>{setForm({...form,supplierId:e.target.value});setErrors(x=>({...x,supplierId:''}))}} error={errors.supplierId}><option value="" disabled>— Select a supplier —</option>{activeSuppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</OrderSelect><Field label="Quantity" required type="number" min="1" max="99999" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})} error={errors.quantity}/><Field label="Notes (optional)" textarea rows="3" placeholder="Add any notes about this order..." value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><Field label="Expected Delivery" type="date" min={new Date().toISOString().slice(0,10)} value={form.expectedDelivery} onChange={e=>setForm({...form,expectedDelivery:e.target.value})}/><div className="modal-actions"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn-primary">Place Order</button></div></form></Modal>
 <Modal isOpen={Boolean(statusOrder)} onClose={()=>setStatusOrder(null)} title="Update Order Status" size="sm"><div className="modal-form"><OrderSelect label="Status" value={status} onChange={e=>setStatus(e.target.value)}><option value="PENDING">Pending</option><option value="COMPLETED">Received</option><option value="CANCELLED">Cancelled</option></OrderSelect><div className="modal-actions"><button className="btn-secondary" onClick={()=>setStatusOrder(null)}>Cancel</button><button className="btn-primary" onClick={saveStatus}>Save</button></div></div></Modal></PageLayout>
}
const title=value=>value.charAt(0)+value.slice(1).toLowerCase();
const formatDate=value=>value?new Date(value).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}):'—';
function OrderSelect({label,required,error,children,...props}){return <label><span>{label}{required&&<b className="required"> *</b>}</span><select {...props}>{children}</select>{error&&<small className="field-error">{error}</small>}</label>}
function Field({label,textarea,error,...props}){return <label><span>{label}</span>{textarea?<textarea {...props}/>:<input {...props}/>} {error&&<small className="field-error">{error}</small>}</label>}
function EmptyOrders({onAdd}){return <div className="proper-empty"><div>▤</div><strong>No orders yet</strong><p>Create a purchase order when stock needs replenishing.</p><button className="btn-primary" onClick={onAdd}>+ Create Order</button></div>}
